### ISSUE TITLE
Resolve Rails 5 Deprecation Warnings

### ISSUE THREAD

**Issue by GrimmOutlook** [ignitebaltimore/ignitespeak#34]
Resolve two deprecation warnings that arose during the upgrade to Rails 4.2.4.

When upgrading to the latest Rails version - 4.2.4 - there were two deprecation warnings that came up.  Both are for the eventual release of Rails 5.  The warnings are as follows:
-  DEPRECATION WARNING: The configuration option config.serve_static_assets has been renamed to config.serve_static_files to clarify its role (it merely enables serving everything in the public folder and is unrelated to the asset pipeline). The serve_static_assets alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in at /Users/davidgrimm/ignitespeak/config/environments/test.rb:11)
-  DEPRECATION WARNING: #deliver is deprecated and will be removed in Rails 5. Use #deliver_now to deliver immediately or #deliver_later to deliver through Active Job. (called from create at /Users/davidgrimm/ignitespeak/app/controllers/proposals_controller.rb:30)

**Comment by subelsky** [comment]
cool! I would like to use `#deliver_now` because I want the proposal submission to fail if we can't deliver the message.
