### ISSUE TITLE
Create ignitespeak-dev google group

### ISSUE THREAD

**Issue by subelsky** [ignitebaltimore/ignitespeak#36]
Need someone to setup a google group for contributors to the project where we can debate, ask questions, help each other with installation, etc etc.

**Comment by subelsky** [comment]
completing the ticket also involves updating the `README`

**Comment by mroswell** [comment]
I'll take this one.

**Comment by mroswell** [comment]
Done. 
- https://groups.google.com/forum/#!forum/ignitespeak-dev 
- https://github.com/ignitebaltimore/ignitespeak/pull/37/files

**Comment by subelsky** [comment]
Thanks!!
